"""created ImageHash model

Revision ID: 00575d7e6617
Revises: dec43e49a9ff
Create Date: 2023-09-14 16:38:38.818328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00575d7e6617'
down_revision = 'dec43e49a9ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_name', sa.String(length=64), nullable=False),
    sa.Column('img_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_info')
    # ### end Alembic commands ###
