"""added is_active col to User model

Revision ID: 8411aa08bee7
Revises: 6ac9fd5feeb1
Create Date: 2023-09-03 00:24:43.527413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8411aa08bee7'
down_revision = '6ac9fd5feeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_info', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
